### PR TITLE
Fix issue #12

### LINKED ISSUE #12: 1.0.4 causes parts of `assets/tests.js` not to be transpiled
In 1.0.4, all the `*.js` files in `app/` appear in `assets/tests.js` without transpilation. Reverting back to 1.0.3 fixes the issue, so maybe it's due to the changes in https://github.com/sir-dunxalot/ember-cli-sass-lint/commit/a433f934de876c8b155804a9d6a1adff7bfa36f9.

I think it's the same issue as https://github.com/ember-cli/ember-cli/issues/7063 (and fixed by https://github.com/billybonks/ember-cli-stylelint/pull/71/files for `ember-cli-stylelint`).

### PR DESCRIPTION
**Pull request by YoranBrondsema**
Fixes #12. I'm not sure how to write a test for this as the SASS linter will work regardless of whether there are JS files in the tree.

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
Thanks!

**Comment by YoranBrondsema** [comment]
@rwwagner90 Do you mind releasing 1.0.5 with this patch? Then I can safely upgrade from 1.0.3 in my own project :-). Thanks!

**Comment by RobbieTheWagner** [comment]
@YoranBrondsema I updated a bunch of dependencies and released 1.0.5. Can you please check if everything works for you on version 1.0.5?

**Comment by YoranBrondsema** [comment]
@rwwagner90 Yep, I updated and it's all good. Thanks a lot!

**Pull request merged**
